/* GeneratedCorpusQueryLanguageParser.java */
/* Generated By:JavaCC: Do not edit this line. GeneratedCorpusQueryLanguageParser.java */
package nl.inl.blacklab.queryParser.corpusql;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import nl.inl.blacklab.queryParser.corpusql.CorpusQueryLanguageParser.ChildRelationStruct;
import nl.inl.blacklab.search.lucene.BLSpanQuery;
import nl.inl.blacklab.search.lucene.SpanQueryPositionFilter.Operation;
import nl.inl.blacklab.search.matchfilter.ConstraintValue;
import nl.inl.blacklab.search.matchfilter.ConstraintValueSymbol;
import nl.inl.blacklab.search.matchfilter.MatchFilterCompare;
import nl.inl.blacklab.search.textpattern.RelationOperatorInfo;
import nl.inl.blacklab.search.textpattern.TextPattern;
import nl.inl.blacklab.search.textpattern.TextPatternAnd;
import nl.inl.blacklab.search.textpattern.TextPatternAnyToken;
import nl.inl.blacklab.search.textpattern.TextPatternCaptureGroup;
import nl.inl.blacklab.search.textpattern.TextPatternCompare;
import nl.inl.blacklab.search.textpattern.TextPatternConstrained;
import nl.inl.blacklab.search.textpattern.TextPatternDefaultValue;
import nl.inl.blacklab.search.textpattern.TextPatternFunctionCall;
import nl.inl.blacklab.search.textpattern.TextPatternImplication;
import nl.inl.blacklab.search.textpattern.TextPatternLook;
import nl.inl.blacklab.search.textpattern.TextPatternNot;
import nl.inl.blacklab.search.textpattern.TextPatternOr;
import nl.inl.blacklab.search.textpattern.TextPatternOverlapping;
import nl.inl.blacklab.search.textpattern.TextPatternPositionFilter;
import nl.inl.blacklab.search.textpattern.TextPatternPropertySelect;
import nl.inl.blacklab.search.textpattern.TextPatternRepetition;
import nl.inl.blacklab.search.textpattern.TextPatternSequence;
import nl.inl.blacklab.search.textpattern.TextPatternSettings;
import nl.inl.blacklab.search.textpattern.TextPatternTags;
import nl.inl.blacklab.search.textpattern.TextPatternTags.Adjust;
import nl.inl.blacklab.search.textpattern.TextPatternValue;
import nl.inl.util.StringUtil;

@SuppressWarnings("all")

public class GeneratedCorpusQueryLanguageParser implements GeneratedCorpusQueryLanguageParserConstants {

    CorpusQueryLanguageParser wrapper;

// --- Grammar rules start here ---

/* a query */
  final public TextPattern query(BCQLParseContext ctx) throws ParseException {TextPattern a = null;
    a = settingsQuery(ctx);
    jj_consume_token(0);
{if ("" != null) return a;}
    throw new Error("Missing return statement in function");
  }

/** A query prefixed with the settings operator
 *  (currently undocumented feature to set e.g. default relation class)
 */
  final public TextPattern settingsQuery(BCQLParseContext ctx) throws ParseException {TextPattern a = null;
    Token settings = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SETTINGS_OP:{
      settings = jj_consume_token(SETTINGS_OP);
      a = settingsQuery(ctx);
// Parse settings operator (of the form "@a=b,c=d,e=f") into a map
        String keyValuesString = settings.toString().substring(1);
        Map<String, String> settingsMap = new LinkedHashMap<String, String>();
        for (String keyValue : keyValuesString.split(",")) {
            String[] keyAndValue = keyValue.split("=");
            if (keyAndValue.length != 2)
                {if (true) throw new IllegalArgumentException("Invalid settings string: " + keyValuesString);}
            settingsMap.put(keyAndValue[0], keyAndValue[1]);
        }
        {if ("" != null) return new TextPatternSettings(settingsMap, a);}
      break;
      }
    case DEFAULT_VALUE:
    case ROOT_DEP_OP:
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:
    case NAME:
    case 30:
    case 31:
    case 34:
    case 39:{
      a = constrainedQuery(ctx);
{if ("" != null) return a;}
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/** A query with a "global" constraint */
  final public TextPattern constrainedQuery(BCQLParseContext ctx) throws ParseException {TextPattern a = null;
    TextPattern b = null;
    a = containingWithinQuery(ctx.withQuotedStringIsQuery(true));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 24:{
      jj_consume_token(24);
      b = constraint(ctx.withQuotedStringIsQuery(false));
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      ;
    }
if (b == null)
            {if ("" != null) return a;}
        {if ("" != null) return new TextPatternConstrained(a, b);}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern constraint(BCQLParseContext ctx) throws ParseException {TextPattern a = null, c = null;
    Token b = null;
    a = simpleConstraint(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 46:
    case 47:
    case 48:{
      b = booleanOperator();
      c = constraint(ctx);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
if (b == null)
            {if ("" != null) return a;}
        if (b.toString().equals("->"))
            {if ("" != null) return new TextPatternImplication(a, c);}
        if (b.toString().equals("&"))
            {if ("" != null) return new TextPatternAnd(a, c);}
        {if ("" != null) return new TextPatternOr(a, c);}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern simpleConstraint(BCQLParseContext ctx) throws ParseException {TextPattern v = null, w = null;
    Token b = null;
    v = constraintValue(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:{
      b = comparisonOperator();
      w = constraintValue(ctx.withQuotedStringIsQuery(false));
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
if (b == null)
            {if ("" != null) return v;}
        switch (b.toString()) {
        case "=":
        case "!=":
        case ">=":
        case "<=":
        case ">":
        case "<":
            MatchFilterCompare.Operator op = MatchFilterCompare.Operator.fromSymbol(b.toString());
            {if ("" != null) return new TextPatternCompare(v, w, op);}
        default:
            {if (true) throw new UnsupportedOperationException("Unknown comparison operator: " + b.toString());}
        }
    throw new Error("Missing return statement in function");
  }

  final public Token comparisonOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 25:{
      t = jj_consume_token(25);
      break;
      }
    case 26:{
      t = jj_consume_token(26);
      break;
      }
    case 27:{
      t = jj_consume_token(27);
      break;
      }
    case 28:{
      t = jj_consume_token(28);
      break;
      }
    case 29:{
      t = jj_consume_token(29);
      break;
      }
    case 30:{
      t = jj_consume_token(30);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern constraintValue(BCQLParseContext ctx) throws ParseException {TextPattern tp = null;
    List<TextPattern> queryFuncParamList = null;
    Token annotName = null;
    Token s = null;
    if (jj_2_1(2)) {
      tp = simpleConstraintValue(ctx);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 31:{
        jj_consume_token(31);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IN:
        case QUOTED_STRING:
        case SINGLE_QUOTED_STRING:
        case NAME:
        case INTEGER:
        case 31:
        case 34:{
          queryFuncParamList = commaSeparatedParamListConstraint(ctx);
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          ;
        }
        jj_consume_token(32);
if (!(tp instanceof TextPatternValue))
                {if (true) throw new IllegalArgumentException("Function call needs a function name");}
            TextPatternValue tpv = (TextPatternValue)tp;
            if (!(tpv.getValue() instanceof ConstraintValueSymbol))
                {if (true) throw new IllegalArgumentException("Function call needs a function name");}
            ConstraintValueSymbol cvs = (ConstraintValueSymbol)tpv.getValue();
            {if ("" != null) return new TextPatternFunctionCall(cvs.getValue(), queryFuncParamList);}
        break;
        }
      case 33:{
        jj_consume_token(33);
        annotName = jj_consume_token(NAME);
TextPatternValue annot = new TextPatternValue(ConstraintValue.symbol(annotName.toString()));
            {if ("" != null) return new TextPatternPropertySelect(tp, annot);}
        break;
        }
      default:
        jj_la1[6] = jj_gen;
{if ("" != null) return tp;}
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 34:{
        jj_consume_token(34);
        tp = constraintValue(ctx);
{if ("" != null) return new TextPatternNot(tp);}
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public List<TextPattern> commaSeparatedParamListConstraint(BCQLParseContext ctx) throws ParseException {TextPattern q = null;
    List<TextPattern> p = new ArrayList<TextPattern>();
    q = constraintValue(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 35:{
      jj_consume_token(35);
      p = commaSeparatedParamListConstraint(ctx);
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
p.add(0, q);
        {if ("" != null) return p;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern simpleConstraintValue(BCQLParseContext ctx) throws ParseException {TextPattern v = null;
    String q = null;
    Token s = null;
    Integer[] mv = null;
    String l = null;
    Token i = null;
    Token tMin = null, tMax = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:{
      q = quotedString();
if (ctx.isQuotedStringQuery()) {
            // Outside token brackets in query part. Interpret as a query on the default annotation.
            // (i.e. "cow" means [word="cow"] in BCQL)
            {if ("" != null) return new TextPatternCompare(TextPatternDefaultValue.get(), TextPatternValue.fromObject(q),
                    MatchFilterCompare.Operator.EQUAL);}
        }
        {if ("" != null) return TextPatternValue.fromObject(q);}
      break;
      }
    case INTEGER:{
      s = jj_consume_token(INTEGER);
{if ("" != null) return TextPatternValue.fromObject(Integer.parseInt(s.toString()));}
      break;
      }
    case IN:{
      mv = inIntegerRange();
{if ("" != null) return TextPatternValue.fromObject(mv);}
      break;
      }
    case NAME:{
      l = captureLabel();
{if ("" != null) return new TextPatternValue(ConstraintValue.symbol(l));}
      break;
      }
    case 31:{
      jj_consume_token(31);
      v = constraint(ctx);
      jj_consume_token(32);
{if ("" != null) return v;}
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

/** A query using the containing/within operator. */
  final public TextPattern containingWithinQuery(BCQLParseContext ctx) throws ParseException {TextPattern a = null, b = null;
    Token op = null;
    Operation oper = Operation.CONTAINING;
    a = relationQuery(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WITHIN:
    case CONTAINING:
    case OVERLAP:{
      op = containingWithinOperator();
      b = containingWithinQuery(ctx);
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
if (op == null)
        {if ("" != null) return a;}
    if (op.toString().equals("within")) {
        // a within b
        oper = Operation.WITHIN;
    } else if (op.toString().equals("overlap")) {
        // a overlaps b
        {if ("" != null) return new TextPatternOverlapping(a, b, op.toString());}
    }

    {if ("" != null) return new TextPatternPositionFilter(a, b, oper);}
    throw new Error("Missing return statement in function");
  }

  final public Token containingWithinOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case WITHIN:{
      t = jj_consume_token(WITHIN);
      break;
      }
    case CONTAINING:{
      t = jj_consume_token(CONTAINING);
      break;
      }
    case OVERLAP:{
      t = jj_consume_token(OVERLAP);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

/** A relation query (e.g. dependency relations / parallel corpus) */
  final public TextPattern relationQuery(BCQLParseContext ctx) throws ParseException {TextPattern parent = null;
    ChildRelationStruct childRel = null;
    List<ChildRelationStruct> childRels = new ArrayList<ChildRelationStruct>();
    String relType = null;
    if (jj_2_4(3)) {
      parent = booleanQuery(ctx);
      if (jj_2_3(3)) {
        childRel = childRelation(ctx);
childRels.add(childRel);
        label_1:
        while (true) {
          if (jj_2_2(2147483647)) {
            ;
          } else {
            break label_1;
          }
          jj_consume_token(36);
          childRel = childRelation(ctx);
childRels.add(childRel);
        }
      } else {
        ;
      }
if (childRels.isEmpty())
            {if ("" != null) return parent;}
        {if ("" != null) return wrapper.relationQuery(parent, childRels);}
    } else if (jj_2_5(3)) {
      parent = rootRelationType(ctx);
{if ("" != null) return parent;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ChildRelationStruct childRelation(BCQLParseContext ctx) throws ParseException {RelationOperatorInfo relType = null;
    TextPattern target = null;
    String label = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      label = captureLabel();
      jj_consume_token(37);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
    relType = relationType();
    target = relationQuery(ctx);
{if ("" != null) return new ChildRelationStruct(relType, target, label);}
    throw new Error("Missing return statement in function");
  }

  final public RelationOperatorInfo relationType() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEP_OP:{
      t = jj_consume_token(DEP_OP);
      break;
      }
    case ALIGNMENT_OP:{
      t = jj_consume_token(ALIGNMENT_OP);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return RelationOperatorInfo.fromOperator(t.toString());}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern rootRelationType(BCQLParseContext ctx) throws ParseException {Token t = null;
    TextPattern target = null;
    String label = "";
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      label = captureLabel();
      jj_consume_token(37);
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
    t = jj_consume_token(ROOT_DEP_OP);
    target = relationQuery(ctx);
RelationOperatorInfo relType = RelationOperatorInfo.fromOperator(t.toString());
        {if ("" != null) return wrapper.rootRelationQuery(new ChildRelationStruct(relType, target, label));}
    throw new Error("Missing return statement in function");
  }

/* a start or self-closing tag tag such as <s> or <s/> (for finding XML elements).
 * Note that it returns one TextPattern, but if it's in [0] that means it's a start
 * tag; if it's in [1] it's a self-closing tag.
 */
  final public TextPattern tag(BCQLParseContext ctx) throws ParseException {Token tagName, endTagSlash = null, selfCloseSlash = null;
    Map<String, TextPattern> attr = new HashMap<String, TextPattern>();
    jj_consume_token(30);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 38:{
      endTagSlash = jj_consume_token(38);
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NAME:{
      tagName = jj_consume_token(NAME);
      break;
      }
    case QUOTED_STRING:{
      tagName = jj_consume_token(QUOTED_STRING);
      break;
      }
    case SINGLE_QUOTED_STRING:{
      tagName = jj_consume_token(SINGLE_QUOTED_STRING);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_2;
      }
      attributes(ctx, attr);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 38:{
      selfCloseSlash = jj_consume_token(38);
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    jj_consume_token(29);
if (endTagSlash != null && selfCloseSlash != null) {
            {if (true) throw new MalformedTagException();}
        }
        TextPatternTags.Adjust adjust;
        if (selfCloseSlash != null)
            adjust = Adjust.FULL_TAG;
        else
            adjust = Adjust.LEADING_EDGE;
        if (endTagSlash != null)
            adjust = Adjust.TRAILING_EDGE;
        String tag = tagName.toString();
        if (tag.charAt(0) == '"' || tag.charAt(0) == '\'') {
            // Quoted tag name: interpret as regex
            tag = wrapper.getRegexFromQuotedString(tag);
        } else {
            // Normal tag name: interpret as literal (so i.e. '.' is just a dot, not 'any character')
            tag = StringUtil.escapeLuceneRegexCharacters(tag);
        }
        {if ("" != null) return new TextPatternTags(tag, attr, adjust, "");}
    throw new Error("Missing return statement in function");
  }

  final public String quotedString() throws ParseException {Token a;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:{
      a = jj_consume_token(QUOTED_STRING);
      break;
      }
    case SINGLE_QUOTED_STRING:{
      a = jj_consume_token(SINGLE_QUOTED_STRING);
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return wrapper.getRegexFromQuotedString(a.toString());}
    throw new Error("Missing return statement in function");
  }

  final public void attributes(BCQLParseContext ctx, Map<String, TextPattern> attr) throws ParseException {Token name;
    String quotedString = null;
    Integer[] intRange = null;
    TextPattern value = null;
    name = jj_consume_token(NAME);
    jj_consume_token(25);
    value = constraintValue(ctx.withQuotedStringIsQuery(false));
attr.put(name.toString(), value);
  }

  final public Integer[] inIntegerRange() throws ParseException {Token tMin, tMax;
    jj_consume_token(IN);
    jj_consume_token(39);
    tMin = jj_consume_token(INTEGER);
    jj_consume_token(35);
    tMax = jj_consume_token(INTEGER);
    jj_consume_token(40);
int min = Integer.parseInt(tMin.toString());
        int max = Integer.parseInt(tMax.toString());
        {if ("" != null) return new Integer[] {min, max};}
    throw new Error("Missing return statement in function");
  }

/* a repetition specifier */
  final public Integer[] repetitionAmount() throws ParseException {Token t = null, t2 = null;
    Integer[] minMax = new Integer[2];
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 41:{
      jj_consume_token(41);
minMax[0] = 0; minMax[1] = BLSpanQuery.MAX_UNLIMITED; {if ("" != null) return minMax;}
      break;
      }
    case 42:{
      jj_consume_token(42);
minMax[0] = 1; minMax[1] = BLSpanQuery.MAX_UNLIMITED; {if ("" != null) return minMax;}
      break;
      }
    case 43:{
      jj_consume_token(43);
minMax[0] = 0; minMax[1] = 1; {if ("" != null) return minMax;}
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      if (jj_2_6(3)) {
        jj_consume_token(44);
        t = jj_consume_token(INTEGER);
        jj_consume_token(45);
minMax[0] = minMax[1] = wrapper.num(t); {if ("" != null) return minMax;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 44:{
          jj_consume_token(44);
          t = jj_consume_token(INTEGER);
          jj_consume_token(35);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case INTEGER:{
            t2 = jj_consume_token(INTEGER);
            break;
            }
          default:
            jj_la1[20] = jj_gen;
            ;
          }
          jj_consume_token(45);
minMax[0] = wrapper.num(t);
        if (t2 == null)
            minMax[1] = BLSpanQuery.MAX_UNLIMITED;
        else
            minMax[1] = wrapper.num(t2);
        {if ("" != null) return minMax;}
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
  }

/* one or more sequence(s) combined using boolean (& and |) operators  */
  final public TextPattern booleanQuery(BCQLParseContext ctx) throws ParseException {TextPattern query = null, rest = null;
    Token b = null;
    query = sequence(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 46:
    case 47:
    case 48:{
      b = booleanOperator();
      rest = booleanQuery(ctx);
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
if (b == null)
            {if ("" != null) return query;}
        if (b.toString().equals("->"))
            {if (true) throw new UnsupportedOperationException("Implication operator only supported within global constraints");}
        if (b.toString().equals("&"))
            {if ("" != null) return new TextPatternAnd(query, rest);}
        {if ("" != null) return new TextPatternOr(query, rest);}
    throw new Error("Missing return statement in function");
  }

/* boolean operator: and, or or implication */
  final public Token booleanOperator() throws ParseException {Token t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 46:{
      t = jj_consume_token(46);
      break;
      }
    case 47:{
      t = jj_consume_token(47);
      break;
      }
    case 48:{
      t = jj_consume_token(48);
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
  }

/* a sequence of token constraints */
  final public TextPattern sequence(BCQLParseContext ctx) throws ParseException {TextPattern query = null;
    TextPattern following = null;
    query = captureQuery(ctx);
    if (jj_2_7(3)) {
      following = sequence(ctx);
query = new TextPatternSequence(query, following);
    } else {
      ;
    }
{if ("" != null) return query;}
    throw new Error("Missing return statement in function");
  }

/* sequence part: one part in a sequence, possibly with a repetition operator */
  final public TextPattern captureQuery(BCQLParseContext ctx) throws ParseException {TextPattern m = null;
    String label = null;
    if (jj_2_8(2)) {
      m = sequencePartNoCapture(ctx);
{if ("" != null) return m;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NAME:{
        label = captureLabel();
        jj_consume_token(37);
        m = sequencePartNoCapture(ctx);
{if ("" != null) return TextPatternCaptureGroup.get(m, label);}
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

/* sequence part: one part in a sequence, possibly with a repetition operator */
  final public TextPattern sequencePartNoCapture(BCQLParseContext ctx) throws ParseException {TextPattern m = null;
    Integer[] rep = null;
    Token lookaheadOp = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULT_VALUE:
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:
    case NAME:
    case 30:
    case 31:
    case 39:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 30:{
        m = tag(ctx);
        break;
        }
      case DEFAULT_VALUE:
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case 39:{
        m = position(ctx);
        break;
        }
      case 31:{
        jj_consume_token(31);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case LOOKAHEAD_OP:{
          lookaheadOp = jj_consume_token(LOOKAHEAD_OP);
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          ;
        }
        /* lookahead/lookbehind? */
                    m = constrainedQuery(ctx);
if (lookaheadOp != null) {
                    // For lookahead/lookbehind, we need zero-length matches of either the leading or trailing edge.
                    String op = lookaheadOp.toString();
                    boolean behind = op.contains("<");
                    boolean negative = op.contains("!");
                    m = new TextPatternLook(m, behind, negative);
                }
        jj_consume_token(32);
        break;
        }
      case NAME:{
        m = queryFunctionCall(ctx);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_3:
      while (true) {
        if (jj_2_9(6)) {
          ;
        } else {
          break label_3;
        }
        rep = repetitionAmount();
if (rep[0] < 0 || rep[1] < 0)
            {if (true) throw new IllegalArgumentException("Repetition amounts must be non-negative");}
        if (m instanceof TextPatternAnyToken) {
            TextPatternAnyToken any = (TextPatternAnyToken)m;
            m = any.repeat(rep[0], rep[1]);
        } else {
            m = TextPatternRepetition.get(m, rep[0], rep[1]);
        }
      }
{if ("" != null) return m;}
      break;
      }
    case 34:{
      jj_consume_token(34);
      m = sequencePartNoCapture(ctx);
{if ("" != null) return new TextPatternNot(m);}
      break;
      }
    default:
      jj_la1[28] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public TextPattern queryFunctionCall(BCQLParseContext ctx) throws ParseException {Token func = null;
    List<TextPattern> queryFuncParamList = Collections.emptyList();
    func = jj_consume_token(NAME);
    jj_consume_token(31);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IN:
    case DEFAULT_VALUE:
    case ROOT_DEP_OP:
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:
    case NAME:
    case INTEGER:
    case 30:
    case 31:
    case 34:
    case 39:{
      queryFuncParamList = commaSeparatedParamList(ctx);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    jj_consume_token(32);
{if ("" != null) return new TextPatternFunctionCall(func.toString(), queryFuncParamList);}
    throw new Error("Missing return statement in function");
  }

  final public List<TextPattern> commaSeparatedParamList(BCQLParseContext ctx) throws ParseException {TextPattern q = null;
    List<TextPattern> p = new ArrayList<TextPattern>();
    q = functionParam(ctx);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case 35:{
      jj_consume_token(35);
      p = commaSeparatedParamList(ctx);
      break;
      }
    default:
      jj_la1[30] = jj_gen;
      ;
    }
p.add(0, q);
        {if ("" != null) return p;}
    throw new Error("Missing return statement in function");
  }

  final public TextPattern functionParam(BCQLParseContext ctx) throws ParseException {TextPattern q;
    Token t = null;
    if (jj_2_10(2)) {
      q = constrainedQuery(ctx);
// A TextPattern or a string (parsed into a TextPattern). If the parameter type is string (we don't know that
        // here), the query will be decoded back to a string later.
        {if ("" != null) return q;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IN:
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case NAME:
      case INTEGER:
      case 31:
      case 34:{
        q = constraintValue(ctx);
{if ("" != null) return q;}
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final public String captureLabel() throws ParseException {Token l = null;
    l = jj_consume_token(NAME);
{if ("" != null) return l.toString();}
    throw new Error("Missing return statement in function");
  }

/* position: a simple attribute value or complex attribute expression between square brackets */
  final public TextPattern position(BCQLParseContext ctx) throws ParseException {TextPattern m = null;
    String f = null;
    String t = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case QUOTED_STRING:
    case SINGLE_QUOTED_STRING:{
      t = quotedString();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FLAGS:{
        f = flags();
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        ;
      }
if (ctx.isQuotedStringQuery()) {
            // Outside token brackets in query part. Interpret as a query on the default annotation.
            // (i.e. "cow" means [word="cow"] in BCQL)
            {if ("" != null) return new TextPatternCompare(TextPatternDefaultValue.get(), TextPatternValue.fromObject(t),
                    MatchFilterCompare.Operator.EQUAL);}
        }
        {if ("" != null) return TextPatternValue.fromObject(t.toString());}
      break;
      }
    case DEFAULT_VALUE:{
      jj_consume_token(DEFAULT_VALUE);
{if ("" != null) return TextPatternDefaultValue.get();}
      break;
      }
    case 39:{
      jj_consume_token(39);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IN:
      case QUOTED_STRING:
      case SINGLE_QUOTED_STRING:
      case NAME:
      case INTEGER:
      case 31:
      case 34:{
        m = constraint(ctx);
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        ;
      }
      jj_consume_token(40);
if (m == null)
            {if ("" != null) return new TextPatternAnyToken(1, 1);}
        {if ("" != null) return m;}
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public String flags() throws ParseException {Token f;
    f = jj_consume_token(FLAGS);
{if ("" != null) return f.toString().substring(1);}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_3R_38()
 {
    if (jj_3R_46()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_64()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_21()) jj_scanpos = xsp;
    if (jj_3R_22()) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) return true;
    }
    }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_9()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) return true;
    }
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_12()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_11()) return true;
    return false;
  }

  private boolean jj_3R_40()
 {
    if (jj_3R_37()) return true;
    if (jj_scan_token(37)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_15()
 {
    if (jj_3R_33()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_34()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_9()
 {
    if (jj_scan_token(36)) return true;
    return false;
  }

  private boolean jj_3R_26()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_8()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) return true;
    }
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_8()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_9()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_23()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) return true;
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_10()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_12()
 {
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_7()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_24()
 {
    if (jj_3R_39()) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_45()
 {
    if (jj_3R_50()) return true;
    return false;
  }

  private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) {
    jj_scanpos = xsp;
    if (jj_scan_token(48)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_50()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(7)) {
    jj_scanpos = xsp;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_59()
 {
    if (jj_3R_61()) return true;
    return false;
  }

  private boolean jj_3R_10()
 {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_24()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_33()
 {
    if (jj_3R_23()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_20()
 {
    if (jj_scan_token(31)) return true;
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_58()
 {
    if (jj_scan_token(FLAGS)) return true;
    return false;
  }

  private boolean jj_3R_19()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  private boolean jj_3R_18()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  private boolean jj_3R_32()
 {
    if (jj_scan_token(44)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(35)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(22)) jj_scanpos = xsp;
    if (jj_scan_token(45)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(44)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(45)) return true;
    return false;
  }

  private boolean jj_3R_31()
 {
    if (jj_scan_token(43)) return true;
    return false;
  }

  private boolean jj_3R_30()
 {
    if (jj_scan_token(42)) return true;
    return false;
  }

  private boolean jj_3R_56()
 {
    if (jj_3R_58()) return true;
    return false;
  }

  private boolean jj_3R_17()
 {
    if (jj_scan_token(INTEGER)) return true;
    return false;
  }

  private boolean jj_3R_14()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_29()) {
    jj_scanpos = xsp;
    if (jj_3R_30()) {
    jj_scanpos = xsp;
    if (jj_3R_31()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3R_32()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_29()
 {
    if (jj_scan_token(41)) return true;
    return false;
  }

  private boolean jj_3R_57()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  private boolean jj_3R_54()
 {
    if (jj_scan_token(39)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_57()) jj_scanpos = xsp;
    if (jj_scan_token(40)) return true;
    return false;
  }

  private boolean jj_3R_53()
 {
    if (jj_scan_token(DEFAULT_VALUE)) return true;
    return false;
  }

  private boolean jj_3R_16()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  private boolean jj_3R_4()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) {
    jj_scanpos = xsp;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_36()
 {
    if (jj_scan_token(IN)) return true;
    if (jj_scan_token(39)) return true;
    return false;
  }

  private boolean jj_3R_48()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_52()
 {
    if (jj_3R_35()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_56()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_61()
 {
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3R_37()
 {
    if (jj_scan_token(NAME)) return true;
    return false;
  }

  private boolean jj_3R_7()
 {
    return false;
  }

  private boolean jj_3R_55()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3R_65()
 {
    if (jj_3R_51()) return true;
    return false;
  }

  private boolean jj_3R_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    return false;
  }

  private boolean jj_3R_6()
 {
    if (jj_scan_token(33)) return true;
    return false;
  }

  private boolean jj_3R_63()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_10()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) return true;
    }
    return false;
  }

  private boolean jj_3_10()
 {
    if (jj_3R_15()) return true;
    return false;
  }

  private boolean jj_3R_60()
 {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_5()
 {
    if (jj_scan_token(31)) return true;
    return false;
  }

  private boolean jj_3R_62()
 {
    if (jj_3R_63()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_4()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_5()) {
    jj_scanpos = xsp;
    if (jj_3R_6()) {
    jj_scanpos = xsp;
    if (jj_3R_7()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_51()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    return false;
  }

  private boolean jj_3R_34()
 {
    if (jj_scan_token(24)) return true;
    return false;
  }

  private boolean jj_3R_47()
 {
    if (jj_scan_token(30)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(20)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) return true;
    }
    }
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_59()) { jj_scanpos = xsp; break; }
    }
    xsp = jj_scanpos;
    if (jj_scan_token(38)) jj_scanpos = xsp;
    if (jj_scan_token(29)) return true;
    return false;
  }

  private boolean jj_3R_66()
 {
    if (jj_3R_67()) return true;
    return false;
  }

  private boolean jj_3R_67()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) {
    jj_scanpos = xsp;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_49()
 {
    if (jj_scan_token(NAME)) return true;
    if (jj_scan_token(31)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) jj_scanpos = xsp;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3R_28()
 {
    if (jj_scan_token(34)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  private boolean jj_3R_25()
 {
    if (jj_3R_37()) return true;
    if (jj_scan_token(37)) return true;
    return false;
  }

  private boolean jj_3R_64()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  private boolean jj_3R_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_25()) jj_scanpos = xsp;
    if (jj_scan_token(ROOT_DEP_OP)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3_9()
 {
    if (jj_3R_14()) return true;
    return false;
  }

  private boolean jj_3R_44()
 {
    if (jj_3R_49()) return true;
    return false;
  }

  private boolean jj_3R_46()
 {
    if (jj_3R_51()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_66()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(15)) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) return true;
    }
    return false;
  }

  private boolean jj_3R_43()
 {
    if (jj_scan_token(31)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(17)) jj_scanpos = xsp;
    if (jj_3R_15()) return true;
    if (jj_scan_token(32)) return true;
    return false;
  }

  private boolean jj_3R_42()
 {
    if (jj_3R_48()) return true;
    return false;
  }

  private boolean jj_3R_41()
 {
    if (jj_3R_47()) return true;
    return false;
  }

  private boolean jj_3R_21()
 {
    if (jj_3R_37()) return true;
    if (jj_scan_token(37)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GeneratedCorpusQueryLanguageParserTokenManager token_source;
  JavaCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[35];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc09c6000,0x1000000,0x0,0x7e000000,0x7e000000,0x805c0400,0x80000000,0x0,0x0,0x805c0400,0x380,0x380,0x100000,0x18000,0x100000,0x0,0x1c0000,0x100000,0x0,0xc0000,0x400000,0x0,0x0,0x0,0x0,0x100000,0x20000,0xc01c2000,0xc01c2000,0xc05c6400,0x0,0x805c0400,0x200000,0x805c0400,0xc2000,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x84,0x0,0x1c000,0x0,0x0,0x4,0x2,0x4,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x40,0x0,0x0,0x40,0x0,0x0,0xe00,0x1000,0x1c000,0x1c000,0x0,0x0,0x80,0x84,0x84,0x8,0x4,0x0,0x4,0x80,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[10];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GeneratedCorpusQueryLanguageParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GeneratedCorpusQueryLanguageParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new JavaCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GeneratedCorpusQueryLanguageParser(java.io.Reader stream) {
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
      jj_input_stream = new JavaCharStream(stream, 1, 1);
   } else {
      jj_input_stream.ReInit(stream, 1, 1);
   }
   if (token_source == null) {
      token_source = new GeneratedCorpusQueryLanguageParserTokenManager(jj_input_stream);
   }

    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GeneratedCorpusQueryLanguageParser(GeneratedCorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GeneratedCorpusQueryLanguageParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 35; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk_f() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) {
       return;
    }

    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];

      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }

      for (int[] oldentry : jj_expentries) {
        if (oldentry.length == jj_expentry.length) {
          boolean isMatched = true;

          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              isMatched = false;
              break;
            }

          }
          if (isMatched) {
            jj_expentries.add(jj_expentry);
            break;
          }
        }
      }

      if (pos != 0) {
        jj_lasttokens[(jj_endpos = pos) - 1] = kind;
      }
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[49];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 35; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 49; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 10; i++) {
      try {
        JJCalls p = jj_2_rtns[i];

        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
            switch (i) {
              case 0: jj_3_1(); break;
              case 1: jj_3_2(); break;
              case 2: jj_3_3(); break;
              case 3: jj_3_4(); break;
              case 4: jj_3_5(); break;
              case 5: jj_3_6(); break;
              case 6: jj_3_7(); break;
              case 7: jj_3_8(); break;
              case 8: jj_3_9(); break;
              case 9: jj_3_10(); break;
            }
          }
          p = p.next;
        } while (p != null);

        } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }

    p.gen = jj_gen + xla - jj_la; 
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
