# Docker Compose development overrides for BlackLab
# (configure JPDA to allow remote JVM debugging)

version: '3.9'

services:

  server:

    # Environment variables to pass to the container
    environment:
      # JPDA settings, to enable remote debugging
      - JPDA_ADDRESS=*:5005
      - JPDA_TRANSPORT=dt_socket

    # Start Tomcat with JPDA enabled
    command: catalina.sh jpda run

    # Map JPDA port
    ports:
      - "5005:5005"

  solr:
      ports:
          # Solr runs on this port
          - "8983:8983"
          # Allow us to attach to the JVM using JDWP for remote debugging
          - "5005:5005"
      environment:
          # Enable JDWP remote debugging on port 5005
          - "SOLR_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
