---
# BlackLab Server config file
# ===============================================================

# Where indexes can be found
# (list directories whose subdirectories are indexes, or directories containing a single index)
indexLocations:
- /data/index

userIndexes: /data/user-index
