/*

Corpus Query Language (CQL) parser definition.

javacc is used to generate Java code from this parser definition.

*/

options 
{
    STATIC=false;
    JAVA_UNICODE_ESCAPE=true;
    //USER_CHAR_STREAM=true;

    // Debug options
    //DEBUG_PARSER = true;
    //DEBUG_LOOKAHEAD = true;
    //DEBUG_TOKEN_MANAGER = true;
}

PARSER_BEGIN(GeneratedCorpusQueryLanguageParser)

package nl.inl.blacklab.queryParser.corpusql;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import nl.inl.blacklab.queryParser.corpusql.CorpusQueryLanguageParser.ChildRelationStruct;
import nl.inl.blacklab.queryParser.corpusql.BCQLParseContext;
import nl.inl.blacklab.search.indexmetadata.MatchSensitivity;
import nl.inl.blacklab.search.lucene.BLSpanQuery;
import nl.inl.blacklab.search.lucene.SpanQueryPositionFilter.Operation;
import nl.inl.blacklab.search.matchfilter.ConstraintValueSymbol;
import nl.inl.blacklab.search.matchfilter.MatchFilterCompare;
import nl.inl.blacklab.search.matchfilter.ConstraintValue;
import nl.inl.blacklab.search.matchfilter.MatchFilterFunctionCall;
import nl.inl.blacklab.search.textpattern.RelationOperatorInfo;
import nl.inl.blacklab.search.textpattern.TextPattern;
import nl.inl.blacklab.search.textpattern.TextPatternAnd;
import nl.inl.blacklab.search.textpattern.TextPatternAnyToken;
import nl.inl.blacklab.search.textpattern.TextPatternCaptureGroup;
import nl.inl.blacklab.search.textpattern.TextPatternCompare;
import nl.inl.blacklab.search.textpattern.TextPatternConstrained;
import nl.inl.blacklab.search.textpattern.TextPatternDefaultValue;
import nl.inl.blacklab.search.textpattern.TextPatternImplication;
import nl.inl.blacklab.search.textpattern.TextPatternLook;
import nl.inl.blacklab.search.textpattern.TextPatternNot;
import nl.inl.blacklab.search.textpattern.TextPatternOr;
import nl.inl.blacklab.search.textpattern.TextPatternOverlapping;
import nl.inl.blacklab.search.textpattern.TextPatternPositionFilter;
import nl.inl.blacklab.search.textpattern.TextPatternFunctionCall;
import nl.inl.blacklab.search.textpattern.TextPatternRegex;
import nl.inl.blacklab.search.textpattern.TextPatternRepetition;
import nl.inl.blacklab.search.textpattern.TextPatternSequence;
import nl.inl.blacklab.search.textpattern.TextPatternSettings;
import nl.inl.blacklab.search.textpattern.TextPatternTags;
import nl.inl.blacklab.search.textpattern.TextPatternTags.Adjust;
import nl.inl.blacklab.search.textpattern.TextPatternTerm;
import nl.inl.blacklab.search.textpattern.TextPatternPropertySelect;
import nl.inl.blacklab.search.textpattern.TextPatternValue;
import nl.inl.util.StringUtil;

@SuppressWarnings("all")

public class GeneratedCorpusQueryLanguageParser {

    CorpusQueryLanguageParser wrapper;

}

PARSER_END(GeneratedCorpusQueryLanguageParser)

// Skip whitespace and comment
SKIP:
{
    " "
|   "\t"
|   "\n"
|   "\r"
}

/* Comments are 'special tokens': they are not reported, but are available
   for use by the next reported token */
SPECIAL_TOKEN:
{
    <SINGLE_LINE_COMMENT: "#" (~["\n","\r"])* ("\n"|"\r"|"\r\n")? >
|   <MULTI_LINE_COMMENT: "/*" (~["*"] | "*" ~["/"])* "*/">
}

// Token definitions
TOKEN [IGNORE_CASE]:
{
    <WITHIN: "within" >
|   <CONTAINING: "containing" >
|   <OVERLAP: "overlap" >
|   <IN: "in">
|   <TRUE: "true">
|   <FALSE: "false">
|   <DEFAULT_VALUE: "_">

    /* valid are e.g. --> -root-> -.*-> -a-b-> (and same preceded by ^ or !) */
|   <ROOT_DEP_OP: "^-" ( ~["-"] (~["-", " ", "'", "\"", "]"] | "-" ~[">", " ", "'", "\"", "]"] )* )? "->" (["A"-"Z","a"-"z","_","-","0"-"9"])* >
|   <DEP_OP: ("!")? "-" ( ~["-"] (~["-", " ", "'", "\"", "]"] | "-" ~[">", " ", "'", "\"", "]"] )* )? "->" (["A"-"Z","a"-"z","_","-","0"-"9"])* >
|   <ALIGNMENT_OP: "=" ( ~["="] (~["=", " ", "'", "\"", "]"] | "=" ~[">", " ", "'", "\"", "]"] )* )? "=>" (["A"-"Z","a"-"z","_","-","0"-"9"])* ("?")? >

|   <LOOKAHEAD_OP: "?" ("<")? ["=", "!"] >

|   <QUOTED_STRING: ("l")? "\"" (~["\"","\\"] | "\\" ~[] )* "\"" >
|   <SINGLE_QUOTED_STRING: ("l")? "'" (~["'","\\"] | "\\" ~[] )* "'" >

|   <NAME: ["A"-"Z","a"-"z","_"] (["A"-"Z","a"-"z","_","-","0"-"9"])* >
|   <FLAGS: "%" (["c", "C", "d", "D", "l", "L"])+ >
|   <INTEGER: ("-")? (["0"-"9"])+ >
|   <SETTINGS_OP: "@" (["A"-"Z","a"-"z","_","0"-"9"])+ "=" (["A"-"Z","a"-"z","_","0"-"9"])+
                ( "," (["A"-"Z","a"-"z","_","0"-"9"])+ "=" (["A"-"Z","a"-"z","_","0"-"9"])+ )* >
}

// --- Grammar rules start here ---

/* a query */
TextPattern query(BCQLParseContext ctx):
{
    TextPattern a = null;
}
{
    a=settingsQuery(ctx) <EOF>
    {
        return a;
    }
}

/** A query prefixed with the settings operator
 *  (currently undocumented feature to set e.g. default relation class)
 */
TextPattern settingsQuery(BCQLParseContext ctx):
{
    TextPattern a = null;
    Token settings = null;
}
{
    settings=<SETTINGS_OP> a=settingsQuery(ctx)
    {
        // Parse settings operator (of the form "@a=b,c=d,e=f") into a map
        String keyValuesString = settings.toString().substring(1);
        Map<String, String> settingsMap = new LinkedHashMap<String, String>();
        for (String keyValue : keyValuesString.split(",")) {
            String[] keyAndValue = keyValue.split("=");
            if (keyAndValue.length != 2)
                throw new IllegalArgumentException("Invalid settings string: " + keyValuesString);
            settingsMap.put(keyAndValue[0], keyAndValue[1]);
        }
        return new TextPatternSettings(settingsMap, a);
    }
|   a=constrainedQuery(ctx)
    {
        return a;
    }
}

/** A query with a "global" constraint */
TextPattern constrainedQuery(BCQLParseContext ctx):
{
    TextPattern a = null;
    TextPattern b = null;
}
{
    a=containingWithinQuery(ctx.withQuotedStringIsQuery(true)) [ "::" b=constraint(ctx.withQuotedStringIsQuery(false)) ]
    {
        if (b == null)
            return a;
        return new TextPatternConstrained(a, b);
    }
}

TextPattern constraint(BCQLParseContext ctx):
{
    TextPattern a = null, c = null;
    Token b = null;
}
{
    a=simpleConstraint(ctx) [ b=booleanOperator() c=constraint(ctx) ]
    {
        if (b == null)
            return a;
        if (b.toString().equals("->"))
            return new TextPatternImplication(a, c);
        if (b.toString().equals("&"))
            return new TextPatternAnd(a, c);
        return new TextPatternOr(a, c);
    }
}

TextPattern simpleConstraint(BCQLParseContext ctx):
{
    TextPattern v = null, w = null;
    Token b = null;
}
{
    v=constraintValue(ctx) [ b=comparisonOperator() w=constraintValue(ctx.withQuotedStringIsQuery(false)) ]
    {
        if (b == null)
            return v;
        switch (b.toString()) {
        case "=":
        case "!=":
        case ">=":
        case "<=":
        case ">":
        case "<":
            MatchFilterCompare.Operator op = MatchFilterCompare.Operator.fromSymbol(b.toString());
            return new TextPatternCompare(v, w, op);
        default:
            throw new UnsupportedOperationException("Unknown comparison operator: " + b.toString());
        }
    }
}

Token comparisonOperator():
{
    Token t = null;
}
{
    (t="=" | t="!=" | t=">=" | t="<=" | t=">" | t="<")  { return t; }
}

TextPattern constraintValue(BCQLParseContext ctx):
{
    TextPattern tp = null;
    List<TextPattern> queryFuncParamList = null;
    Token annotName = null;
    Token s = null;
}
{
    LOOKAHEAD(2)
    tp=simpleConstraintValue(ctx)
    (
        "(" [ queryFuncParamList=commaSeparatedParamListConstraint(ctx) ] ")"
        {
            if (!(tp instanceof TextPatternValue))
                throw new IllegalArgumentException("Function call needs a function name");
            TextPatternValue tpv = (TextPatternValue)tp;
            if (!(tpv.getValue() instanceof ConstraintValueSymbol))
                throw new IllegalArgumentException("Function call needs a function name");
            ConstraintValueSymbol cvs = (ConstraintValueSymbol)tpv.getValue();
            return new TextPatternFunctionCall(cvs.getValue(), queryFuncParamList);
        }
    |   "." annotName=<NAME>
        {
            TextPatternValue annot = new TextPatternValue(ConstraintValue.symbol(annotName.toString()));
            return new TextPatternPropertySelect(tp, annot);
        }
    |   /*empty*/
        {
            return tp;
        }
    )
|   "!" tp=constraintValue(ctx)             { return new TextPatternNot(tp); }
}

List<TextPattern> commaSeparatedParamListConstraint(BCQLParseContext ctx):
{
    TextPattern q = null;
    List<TextPattern> p = new ArrayList<TextPattern>();
}
{
    q=constraintValue(ctx) [ "," p=commaSeparatedParamListConstraint(ctx) ]
    {
        p.add(0, q);
        return p;
    }
}

TextPattern simpleConstraintValue(BCQLParseContext ctx):
{
    TextPattern v = null;
    String q = null;
    Token s = null;
    Integer[] mv = null;
    String l = null;
    Token i = null;
    Token tMin = null, tMax = null;
}
{
    q=quotedString()
    {
        if (ctx.isQuotedStringQuery()) {
            // Outside token brackets in query part. Interpret as a query on the default annotation.
            // (i.e. "cow" means [word="cow"] in BCQL)
            return new TextPatternCompare(TextPatternDefaultValue.get(), TextPatternValue.fromObject(q),
                    MatchFilterCompare.Operator.EQUAL);
        }
        return TextPatternValue.fromObject(q);
    }
|   s=<INTEGER>
    {
        return TextPatternValue.fromObject(Integer.parseInt(s.toString()));
    }
|   mv=inIntegerRange()                 { return TextPatternValue.fromObject(mv); }
|   l=captureLabel()                    { return new TextPatternValue(ConstraintValue.symbol(l)); }
|   "(" v=constraint(ctx) ")"              { return v; }
}

/** A query using the containing/within operator. */
TextPattern containingWithinQuery(BCQLParseContext ctx):
{
    TextPattern a = null, b = null;
    Token op = null;
    Operation oper = Operation.CONTAINING;
}
{
    a=relationQuery(ctx) [ op=containingWithinOperator() b=containingWithinQuery(ctx) ]
    {
    if (op == null)
        return a;
    if (op.toString().equals("within")) {
        // a within b
        oper = Operation.WITHIN;
    } else if (op.toString().equals("overlap")) {
        // a overlaps b
        return new TextPatternOverlapping(a, b, op.toString());
    }

    return new TextPatternPositionFilter(a, b, oper);
}
}

Token containingWithinOperator():
{
    Token t = null;
}
{
    (t=<WITHIN> | t=<CONTAINING> | t=<OVERLAP>)
    {
        return t;
    }
}

/** A relation query (e.g. dependency relations / parallel corpus) */
TextPattern relationQuery(BCQLParseContext ctx):
{
    TextPattern parent = null;
    ChildRelationStruct childRel = null;
    List<ChildRelationStruct> childRels = new ArrayList<ChildRelationStruct>();
    String relType = null;
}
{   LOOKAHEAD(3)
    parent=booleanQuery(ctx)
    [
        LOOKAHEAD(3)
        childRel=childRelation(ctx)                        { childRels.add(childRel); }
        /* LOOKAHEAD( ";" ) suppresses dangling-else problem */
        ( LOOKAHEAD( ";" ) ";" childRel=childRelation(ctx) { childRels.add(childRel); } )*
    ]
    {
        if (childRels.isEmpty())
            return parent;
        return wrapper.relationQuery(parent, childRels);
    }
|   LOOKAHEAD(3) parent=rootRelationType(ctx)
    {
        return parent;
    }
}

ChildRelationStruct childRelation(BCQLParseContext ctx):
{
    RelationOperatorInfo relType = null;
    TextPattern target = null;
    String label = "";
}
{
    [ label=captureLabel() ":" ]
    relType=relationType() target=relationQuery(ctx)
    {
        return new ChildRelationStruct(relType, target, label);
    }
}

RelationOperatorInfo relationType():
{
    Token t = null;
}
{
    (t=<DEP_OP> | t=<ALIGNMENT_OP>)
    {
        return RelationOperatorInfo.fromOperator(t.toString());
    }
}

TextPattern rootRelationType(BCQLParseContext ctx):
{
    Token t = null;
    TextPattern target = null;
    String label = "";
}
{
    [ label=captureLabel() ":" ]
    t=<ROOT_DEP_OP> target=relationQuery(ctx)
    {
        RelationOperatorInfo relType = RelationOperatorInfo.fromOperator(t.toString());
        return wrapper.rootRelationQuery(new ChildRelationStruct(relType, target, label));
    }
}


/* a start or self-closing tag tag such as <s> or <s/> (for finding XML elements).
 * Note that it returns one TextPattern, but if it's in [0] that means it's a start
 * tag; if it's in [1] it's a self-closing tag.
 */
TextPattern tag(BCQLParseContext ctx):
{
    Token tagName, endTagSlash = null, selfCloseSlash = null;
    Map<String, TextPattern> attr = new HashMap<String, TextPattern>();
}
{
    "<" (endTagSlash="/")? (tagName=<NAME>|tagName=<QUOTED_STRING>|tagName=<SINGLE_QUOTED_STRING>) ( attributes(ctx, attr) )* (selfCloseSlash="/")? ">"
    {
        if (endTagSlash != null && selfCloseSlash != null) {
            throw new MalformedTagException();
        }
        TextPatternTags.Adjust adjust;
        if (selfCloseSlash != null)
            adjust = Adjust.FULL_TAG;
        else
            adjust = Adjust.LEADING_EDGE;
        if (endTagSlash != null)
            adjust = Adjust.TRAILING_EDGE;
        String tag = tagName.toString();
        if (tag.charAt(0) == '"' || tag.charAt(0) == '\'') {
            // Quoted tag name: interpret as regex
            tag = wrapper.getRegexFromQuotedString(tag);
        } else {
            // Normal tag name: interpret as literal (so i.e. '.' is just a dot, not 'any character')
            tag = StringUtil.escapeLuceneRegexCharacters(tag);
        }
        return new TextPatternTags(tag, attr, adjust, "");
    }
}

String quotedString():
{
    Token a;
}
{
    (a=<QUOTED_STRING> | a=<SINGLE_QUOTED_STRING>)
    {
        return wrapper.getRegexFromQuotedString(a.toString());
    }
}

void attributes(BCQLParseContext ctx, Map<String, TextPattern> attr):
{
    Token name;
    String quotedString = null;
    Integer[] intRange = null;
    TextPattern value = null;
}
{
    name=<NAME> "=" value=constraintValue(ctx.withQuotedStringIsQuery(false))
    {
        attr.put(name.toString(), value);
    }
}

Integer[] inIntegerRange():
{
    Token tMin, tMax;
}
{
    <IN> "[" tMin=<INTEGER> "," tMax=<INTEGER> "]"
    {
        int min = Integer.parseInt(tMin.toString());
        int max = Integer.parseInt(tMax.toString());
        return new Integer[] {min, max};
    }
}

/* a repetition specifier */
Integer[] repetitionAmount():
{
    Token t = null, t2 = null;
    Integer[] minMax = new Integer[2];
}
{
    "*"                                 { minMax[0] = 0; minMax[1] = BLSpanQuery.MAX_UNLIMITED; return minMax; }
|   "+"                                 { minMax[0] = 1; minMax[1] = BLSpanQuery.MAX_UNLIMITED; return minMax; }
|   "?"                                 { minMax[0] = 0; minMax[1] = 1; return minMax; }
|   LOOKAHEAD(3) "{" t=<INTEGER> "}"     { minMax[0] = minMax[1] = wrapper.num(t); return minMax; }
|   "{" t=<INTEGER> "," [ t2=<INTEGER> ] "}"
    {
        minMax[0] = wrapper.num(t);
        if (t2 == null)
            minMax[1] = BLSpanQuery.MAX_UNLIMITED;
        else
            minMax[1] = wrapper.num(t2);
        return minMax;
    }
}

/* one or more sequence(s) combined using boolean (& and |) operators  */
TextPattern booleanQuery(BCQLParseContext ctx):
{
    TextPattern query = null, rest = null;
    Token b = null;
}
{
    query=sequence(ctx) [ b=booleanOperator() rest=booleanQuery(ctx) ]
    {
        if (b == null)
            return query;
        if (b.toString().equals("->"))
            throw new UnsupportedOperationException("Implication operator only supported within global constraints");
        if (b.toString().equals("&"))
            return new TextPatternAnd(query, rest);
        return new TextPatternOr(query, rest);
    }
}

/* boolean operator: and, or or implication */
Token booleanOperator():
{
    Token t = null;
}
{
    (t="&" | t="|" | t="->")  { return t; }
}

/* a sequence of token constraints */
TextPattern sequence(BCQLParseContext ctx):
{
    TextPattern query = null;
    TextPattern following = null;
}
{
    query=captureQuery(ctx) [ LOOKAHEAD(3) following=sequence(ctx) { query = new TextPatternSequence(query, following); } ]
    {
        return query;
    }
}

/* sequence part: one part in a sequence, possibly with a repetition operator */
TextPattern captureQuery(BCQLParseContext ctx):
{
    TextPattern m = null;
    String label = null;
}
{
    LOOKAHEAD(2)
    m=sequencePartNoCapture(ctx)    { return m; }
|   label=captureLabel() ":" m=sequencePartNoCapture(ctx)    { return TextPatternCaptureGroup.get(m, label); }
}


/* sequence part: one part in a sequence, possibly with a repetition operator */
TextPattern sequencePartNoCapture(BCQLParseContext ctx):
{
    TextPattern m = null;
    Integer[] rep = null;
    Token lookaheadOp = null;
}
{
    (
        m=tag(ctx) |
        m=position(ctx) |
        "("
            ( lookaheadOp=<LOOKAHEAD_OP> )?   /* lookahead/lookbehind? */
            m=constrainedQuery(ctx)
            {
                if (lookaheadOp != null) {
                    // For lookahead/lookbehind, we need zero-length matches of either the leading or trailing edge.
                    String op = lookaheadOp.toString();
                    boolean behind = op.contains("<");
                    boolean negative = op.contains("!");
                    m = new TextPatternLook(m, behind, negative);
                }
            }
        ")" |
        m=queryFunctionCall(ctx)
    )
    ( LOOKAHEAD(6) rep=repetitionAmount() {
        if (rep[0] < 0 || rep[1] < 0)
            throw new IllegalArgumentException("Repetition amounts must be non-negative");
        if (m instanceof TextPatternAnyToken) {
            TextPatternAnyToken any = (TextPatternAnyToken)m;
            m = any.repeat(rep[0], rep[1]);
        } else {
            m = TextPatternRepetition.get(m, rep[0], rep[1]);
        }
    } )*
    {
        return m;
    }
|   "!" m=sequencePartNoCapture(ctx)
    {
        return new TextPatternNot(m);
    }
}

TextPattern queryFunctionCall(BCQLParseContext ctx):
{
    Token func = null;
    List<TextPattern> queryFuncParamList = Collections.emptyList();
}
{
    func=<NAME> "(" [ queryFuncParamList=commaSeparatedParamList(ctx) ] ")"
    {
        return new TextPatternFunctionCall(func.toString(), queryFuncParamList);
    }
}

List<TextPattern> commaSeparatedParamList(BCQLParseContext ctx):
{
    TextPattern q = null;
    List<TextPattern> p = new ArrayList<TextPattern>();
}
{
    q=functionParam(ctx) [ "," p=commaSeparatedParamList(ctx) ]
    {
        p.add(0, q);
        return p;
    }
}

TextPattern functionParam(BCQLParseContext ctx):
{
    TextPattern q;
    Token t = null;
}
{   LOOKAHEAD(2)
    q=constrainedQuery(ctx)
    {
        // A TextPattern or a string (parsed into a TextPattern). If the parameter type is string (we don't know that
        // here), the query will be decoded back to a string later.
        return q;
    }
|   q=constraintValue(ctx)    { return q; }
}

String captureLabel():
{
    Token l = null;
}
{
    ( l=<NAME> )
    {
        return l.toString();
    }
}

/* position: a simple attribute value or complex attribute expression between square brackets */
TextPattern position(BCQLParseContext ctx):
{
    TextPattern m = null;
    String f = null;
    String t = null;
}
{
    t=quotedString() [ f=flags()]
    {
        if (ctx.isQuotedStringQuery()) {
            // Outside token brackets in query part. Interpret as a query on the default annotation.
            // (i.e. "cow" means [word="cow"] in BCQL)
            return new TextPatternCompare(TextPatternDefaultValue.get(), TextPatternValue.fromObject(t),
                    MatchFilterCompare.Operator.EQUAL);
        }
        return TextPatternValue.fromObject(t.toString());
    }
|   <DEFAULT_VALUE>                    { return TextPatternDefaultValue.get(); }
|   "[" [ m=constraint(ctx) ] "]"
    {
        if (m == null)
            return new TextPatternAnyToken(1, 1);
        return m;
    }
}

String flags():
{
    Token f;
}
{
    f=<FLAGS> { return f.toString().substring(1); }
}
