package nl.inl.blacklab.exceptions;

/**
 * An Exception generated by BlackLab.
 *
 * This will be the base class of all BlackLab-thrown Exceptions. More
 * specific subclasses can be caught to handle specific situations.
 */
public abstract class BlackLabException extends Exception {

    protected BlackLabException() {
        super();
    }

    protected BlackLabException(String message, Throwable cause) {
        super(message, cause);
    }

    protected BlackLabException(String message) {
        super(message);
    }

    protected BlackLabException(Throwable cause) {
        super(cause);
    }

}
