package nl.inl.blacklab.exceptions;

/**
 * An Exception generated by BlackLab.
 *
 * This is the base class for checked Exceptions thrown by BlackLab. More
 * specific subclasses can be caught to handle specific situations.
 */
public abstract class BlackLabException extends Exception {

    public static RuntimeException wrapRuntime(Throwable e) {
        if (e == null)
            return new RuntimeException("Tried to wrap a null exception");
        if (e instanceof RuntimeException bre)
            return bre;
        return new RuntimeException(e);
    }

    protected BlackLabException() {
        super();
    }

    protected BlackLabException(String message, Throwable cause) {
        super(message, cause);
    }

    protected BlackLabException(String message) {
        super(message);
    }

    protected BlackLabException(Throwable cause) {
        super(cause);
    }
}
